### ISSUE TITLE
[Feature Request] Add blacklist item to sell

### ISSUE THREAD

**Issue by SnowCutieOwO** [EpiCanard/GlobalMarketChest#150]
``` YAML
blacklist:
  item:
    - bedrock
  lore-contain:
    - 'Untradable Item'
  name-contain:
    - '(Untradable)'
```

This is very important for some server with custom items. Thanks!
