### ISSUE TITLE
Creation world - choice between blacklist and whitelist

### ISSUE THREAD

**Issue by EpiCanard** [EpiCanard/GlobalMarketChest#85]
Issue goal: Suggestion

**Description**

Add the possibility to choose between a blacklist or a whitelist for world allowed for shop creation.

Example:
```YAML
CreationWorld:
  # whitelist or blacklist (default blacklist if not specified)
  Type: 'whitelist'
  Worlds:
  - world
  - world_the_end
 ```
